### ISSUE TITLE
Having problem downloading tap-strava

### ISSUE THREAD

**Issue by sorlovsky** [briansloane/tap-strava#1]
Hi Brian,

I am new to singer/stitch ecosystem. I am attempting to use this tool for a project I am working on to visualize strava data.

I am getting this error when I run `pip install tap-strava`. 
```
Could not find a version that satisfies the requirement tap-strava (from versions: )
No matching distribution found for tap-strava
```

Is this project still availabe on `pypi`?

Best,
Simon

**Comment by briansloane** [comment]
Hi @sorlovsky. I actually don't think I put this on PyPi yet, despite what the readme says. Apologies for the confusion.

For now I recommend cloning the repo and installing from the setup.py with something like

`python setup.py install` 

Hope that helps get you started.

**Comment by briansloane** [comment]
@sorlovsky I just packaged and put it up on PyPi as well :-)

https://pypi.org/project/tap-strava/

Thanks for pinging me on this.

**Comment by sorlovsky** [comment]
Successfully pulled packaged from pyi!
```
Successfully installed arrow-0.15.5 pytz-2018.4 singer-python-5.2.1 stravalib-0.10.2 tap-strava-0.0.1 units-0.7
```
thanks!
